apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-config
  labels:
    app: user-api
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
