apiVersion: v1
kind: ConfigMap
metadata:
  name: hw2-config
data:  
---
apiVersion: v1
kind: Secret
metadata:
  name: hw2-secret
type: Opaque
data:
  POSTGRES_HOST: {{ (include "postgresql.fullname" .) | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.service.port | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}