version: '3.4'

networks:
  userapi:
    driver: bridge 

services:
  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    #depends_on:
    #  - "postgres_image"
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    ports:
      - 8080:80
    environment:
      - ConnectionString=Host=postgres_image;Database=users;Username=postgres;Password=qwerty;    
    networks:
      - userapi
  postgres_image:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: users
    networks:
      - userapi
volumes:
  db_volume:
    driver: local